RTE v4: quill v2
mendix/web-widgets pull request #1119
Opened 2024-06-18 13:34 UTC by gjulivan

### Pull request type

---

### Description

2024-10-02 07:54 UTC, samuelreichert reviewed
Do you have screenshots for the PR description?

2024-10-02 13:10 UTC, samuelreichert requested changes

2024-10-02 13:10 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx
> +        }
We have `executeAction()` which helps with the validation to run the onChange, so you can use something like:
```
import { executeAction } from "mendix";

if (onChangeType === "onDataChange") {
    executeAction(onChange)
}
```

2024-10-02 13:10 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/Dialog.tsx
> +    const { getFloatingProps } = useInteractions([click, dismiss, role]);
You could create a hook for that 😄

2024-10-02 13:11 UTC, samuelreichert commented
RTE v4 is looking good! 🎉

2024-10-02 13:51 UTC, gjulivan commented on packages/pluggableWidgets/rich-text-web/src/utils/helpers.ts
> +            }
although there seems no changes here, format.indent have been overriden for getSemanticHTML method
 thus, this will keep being here instead of inside the upper if.

2024-10-02 13:58 UTC, gjulivan commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/Dialog.tsx
> +    const { getFloatingProps } = useInteractions([click, dismiss, role]);
Yes. we can. but "Dialog.tsx" here is already a generic form of dialog for rich text.
I'd rather not take this part out for the sake of taking it out.

2024-10-02 14:00 UTC, gjulivan commented on packages/pluggableWidgets/rich-text-web/src/RichText.tsx
> +        // preset,
done

2024-10-03 07:39 UTC, samuelreichert approved these changes

2024-10-22 08:20 UTC, iobuhov submitted a review, later dismissed

2024-10-28 08:45 UTC, leonardomendix approved these changes

2024-10-28 16:09 UTC, leonardomendix approved these changes

2024-10-28 16:23 UTC, samuelreichert approved these changes

2024-10-28 16:23 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/ImageDialog.tsx
> +                <DialogFooter onSubmit={() => onSubmit(formState)} onClose={onClose}></DialogFooter>
This can be self closing

2024-10-28 16:23 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/LinkDialog.tsx
> +                <DialogFooter onSubmit={() => onSubmit(formState)} onClose={onClose}></DialogFooter>
This can be self closing

2024-10-28 16:23 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/VideoDialog.tsx
> +            <DialogFooter onSubmit={() => onSubmit(formState)} onClose={onClose}></DialogFooter>
This can be self closing

2024-10-28 16:23 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/VideoDialog.tsx
> +            <DialogFooter onSubmit={() => onSubmit(formState)} onClose={onClose}></DialogFooter>
This can be self closing

2024-10-28 16:23 UTC, samuelreichert commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/ViewCodeDialog.tsx
> +                <DialogFooter onSubmit={() => onSubmit(formState)} onClose={onClose}></DialogFooter>
This can be self closing

2024-10-28 16:50 UTC, gjulivan commented on packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/LinkDialog.tsx
> +                <DialogFooter onSubmit={() => onSubmit(formState)} onClose={onClose}></DialogFooter>
not mandatory. purposedly made to allow footer content

2024-10-28 16:50 UTC, merged