[WC-2535]: Fix barcodescanner error on module load
mendix/web-widgets pull request #1128
Opened 2024-06-24 11:55 UTC by HedwigAR

### Pull request type

Bug fix (non-breaking change which fixes an issue)

---

### Description

Currently an issue exists where the module won't load because the reference to the canvas it needs is undefined. This PR changes this reference from a state to a ref, which ensures the reference can be found in the async process.

### What should be covered while testing?
If the camera view appears with crop enabled, it means the canvas reference is not undefined, so the issue is fixed. While this shouldn't impact other features in the widget, it would be good to double-check they all work so we won't have to unpublish the widget again.

2024-06-25 07:57 UTC, gjulivan submitted a review, later dismissed

2024-06-25 08:18 UTC, iobuhov requested changes

2024-06-25 08:18 UTC, iobuhov commented on packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx
>              }}
I would suggest instead, change prop type on line 15, to React.RefObject and pass it as it is without using callback. Callback as a ref it's legacy react approach and in this case it not add any value. Just use ref as it is.

2024-06-25 08:21 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx
>              }}
Alright, thanks for the suggestion, I thought doing that made it too cluttered, and just having the object there would be nicer. I'll change it.

2024-06-25 10:55 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx
>              }}
I changed it, let me know if this is right

2024-06-25 12:38 UTC, iobuhov submitted a review, later dismissed
LGTM

2024-06-27 12:52 UTC, iobuhov approved these changes
LGTM

2024-07-01 12:08 UTC, leonardomendix approved these changes

2024-07-01 12:47 UTC, merged