[WC-1657] Update docker files for the RC testing
mendix/web-widgets pull request #1136
Opened 2024-06-27 12:03 UTC by leonardomendix

### Pull request type

Test related change (New E2E test, test automation, etc.)

---

### Description

Update docker files for the RC testing.

### What should be covered while testing?
RC testing Github workflow should work.

2024-06-27 12:05 UTC, iobuhov commented on automation/run-e2e/docker/mxbuildRC.Dockerfile
> +FROM --platform=$BUILDPLATFORM eclipse-temurin:17-jdk-jammy
You choose this image to have java installed already?

2024-06-27 12:08 UTC, leonardomendix commented on automation/run-e2e/docker/mxbuildRC.Dockerfile
> +FROM --platform=$BUILDPLATFORM eclipse-temurin:17-jdk-jammy
Yeah, exactly!

Because now the mxbuild .net8 is self-contained, thus we don't need a .net image.

2024-06-27 12:08 UTC, iobuhov requested changes

2024-06-27 12:08 UTC, iobuhov commented on automation/run-e2e/docker/mxbuildRC.Dockerfile
> +        linux/amd64) \
Case is duplicated

2024-06-27 12:08 UTC, iobuhov commented on automation/run-e2e/docker/mxbuildRC.Dockerfile
>      apt-get clean && \
Can we replace all && with normal docker RUN statements?

2024-06-27 12:27 UTC, leonardomendix commented on automation/run-e2e/docker/mxbuildRC.Dockerfile
>      apt-get clean && \
I have placed it in the end following what we have in the other commands.

2024-07-01 14:44 UTC, gjulivan approved these changes

2024-07-02 07:45 UTC, merged