[WC-2661] fix charts not resized correctly in a popup page
mendix/web-widgets pull request #1260
Opened 2024-10-10 12:04 UTC by gjulivan

### Pull request type

---

### Description

2024-10-14 10:20 UTC, iobuhov requested changes

2024-10-14 10:20 UTC, iobuhov commented on packages/shared/charts/src/components/ChartWidget.tsx
> +
Looks good, but I think it probably make sense to wrap this `useMemo` and `useResizeObserver` with `useDispatchResizeEffect` hook to make code more readable and couple logical pieces together.

2024-10-14 10:20 UTC, iobuhov commented on packages/shared/charts/src/components/ChartWidget.tsx
> +
Also, I would probably add `useEffect` with `abort` function created by `debounce` to avoid memory leaks.

2024-10-14 14:36 UTC, iobuhov approved these changes
LGTM

2024-10-15 13:49 UTC, leonardomendix approved these changes

2024-10-15 13:51 UTC, merged