[WC-2647]: Fix AutoNumber formatter
mendix/web-widgets pull request #1261
Opened 2024-10-10 14:43 UTC by rahmanunver

### Pull request type

Bug fix (non-breaking change which fixes an issue)

---

### Description
Fixing filters not working for AutoNumber, WIP for falsy values.

2024-10-11 10:12 UTC, iobuhov requested changes

2024-10-11 10:12 UTC, iobuhov commented on packages/shared/widget-plugin-filtering/src/stores/NumberInputFilterStore.ts
> +        this.formatter = formatter;
iI think you should not set formatter on FilterStore. It should be used by NumberArgument internally.

2024-10-11 10:12 UTC, iobuhov commented on packages/shared/widget-plugin-filtering/src/stores/NumberInputFilterStore.ts
> +        this.arg2.updateProps(this.formatter as NumberFormatter);
I feel like we can ignore updating formatter. So you can just remove the whole thing.

2024-10-11 10:12 UTC, iobuhov commented on packages/shared/widget-plugin-filtering/src/stores/NumberInputFilterStore.ts
> +        this.arg2.updateProps(this.formatter as NumberFormatter);
And actually it's a good question that you can ask wtf, weather it's changes or it's safe to keep this object.

2024-10-11 13:47 UTC, rahmanunver commented on packages/shared/widget-plugin-filtering/src/stores/NumberInputFilterStore.ts
> +        this.arg2.updateProps(this.formatter as NumberFormatter);
Got in touch, first impression no changes apart from the top of the props assigning initially, I'd say a valid suggestion from your side.

2024-10-11 14:47 UTC, rahmanunver commented on packages/shared/widget-plugin-filtering/src/stores/NumberInputFilterStore.ts
> +        this.formatter = formatter;
made the change

2024-10-11 14:48 UTC, rahmanunver commented on packages/shared/widget-plugin-filtering/src/stores/NumberInputFilterStore.ts
> +        this.arg2.updateProps(this.formatter as NumberFormatter);
removed the formatter updates

2024-10-11 14:54 UTC, iobuhov commented on packages/shared/widget-plugin-filtering/src/stores/Argument.ts
> +            this._value = (parseResult as any).value;
Why you changing this part? Formatter should work as before I think.

2024-10-11 16:00 UTC, rahmanunver commented on packages/shared/widget-plugin-filtering/src/stores/Argument.ts
> +            this._value = (parseResult as any).value;
If the formatter gets the value as `""` then a `new Big(value)` isn't created, which falls into catch block, eventually leaving the empty filter value unset. Looking for another way to handle this.

2024-10-11 16:45 UTC, iobuhov commented on packages/shared/widget-plugin-filtering/src/stores/Argument.ts
> +            this._value = (parseResult as any).value;
Then we have to fix this in formatter implementation. Just check what is returned from other formatter (Integer e.g.) and do same in the fix

2024-10-14 12:57 UTC, iobuhov approved these changes

2024-10-14 14:38 UTC, leonardomendix approved these changes

2024-10-14 14:38 UTC, merged