WIP: [WC-1608]: add google tag web widget
mendix/web-widgets pull request #263
Opened 2023-01-17 15:24 UTC by r0b1n

### Description

### Pull request checklist

-   [x] All new and existing tests passed
-   [x] I run `lint` command locally and it doesn’t give errors
-   [x] PR title properly formatted `[XX-000]: description`
-   [x] Added record to packages' CHANGELOG.md
-   [x] Bumped package version in `package.json` and `package.xml`
-   [ ] Added a link to related project PRs (atlas, pluggable-widgets-tools, testProject, etc.) (optional)
-   [ ] Created docs PR to [mendix/docs](https://github.com/mendix/docs.git) and added a link (optional)

### Pull request type

-   [ ] No code changes (changes to documentation, CI, metadata, etc)
-   [ ] Dependency changes (any modification to dependencies in `package.json`)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Test related change (New E2E test, test automation, etc.)

### What should be covered while testing?

2023-01-19 18:29 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/package.json
> +  "copyright": "© Mendix Technology BV 2022. All rights reserved.",
We should open one big PR where we update `2022` -> `2023`

2023-01-19 18:41 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/package.json
> +    "appName": "Google Tag Widget",
We probably need to ask Danny, as I never saw widgets, that have "Widget" in the title

2023-01-19 18:41 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/GoogleTag.xml
> +                <description />
Can we add short description? Maybe ask Danny? Or this will be part of feedback?

2023-01-19 18:41 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/commonGtag.ts
> +interface DocumentMxGtag extends Document {
I think it's better to use `declare global`
https://github.com/mendix/web-widgets/search?q=declare+global

Then we probably don't need use `(document as DocumentMxTag)`

2023-01-19 18:41 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/package.json
> +  "copyright": "© Mendix Technology BV 2022. All rights reserved.",
We should probably open one big PR to update all 2022s to 2023s

2023-01-26 09:56 UTC, iobuhov commented
@r0b1n, you need to add `typescript@4.5.4` and `ts-node@^9.0.0` as dev dependency

2023-01-26 10:02 UTC, iobuhov commented
Also, we should add `private: true` in package.json as this package will be not publish on it's own, but as part of module.

2023-01-27 13:20 UTC, iobuhov approved these changes

2023-02-01 08:21 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/utils.ts
> +}
Should we somehow handle this for coming "modern client"? I think this may not work in Mendix 10

2023-02-01 08:22 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/utils.ts
> +    const [needsExecution, setNeedsExecution] = useState<boolean>(executeImmediately);
If we just want to call callback, why we need `useState`? Maybe it's better to use `useRef(executeImmediately)`?

2023-02-01 08:39 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/GoogleTag.tsx
> +    const runCommands = useOnAfterRenderExecution(false, () => {
Do we really need `useOnAfterRenderExecution` here? What the purpose? I think we can remove it and just pass `cb` to `useDojoOnNavigation`.

2023-02-02 11:32 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/utils.ts
> +export function useOnAfterRenderExecution(cb: () => boolean): () => void {
I still can't get why we need `useOnAfterRenderExecution`, @r0b1n , can you explain it a bit?

2023-02-02 15:16 UTC, r0b1n commented on packages/pluggableWidgets/google-tag-web/src/utils.ts
> +export function useOnAfterRenderExecution(cb: () => boolean): () => void {
It took care of re-execution when props are not ready. This is probably not the best custom hook out there, I got rid of it :)

2023-02-02 17:58 UTC, iobuhov requested changes

2023-02-02 17:58 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/GoogleTag.tsx
> +    }
let's use `useRef` for `props.trackPageChanges` and remove if statement. Then we can check it inside callback

2023-02-02 17:58 UTC, iobuhov commented on packages/pluggableWidgets/google-tag-web/src/utils.ts
> +}
Same, let's move `window.dojo` check inside `useEffect` callback

2023-02-03 08:40 UTC, r0b1n commented on packages/pluggableWidgets/google-tag-web/src/GoogleTag.tsx
> +    }
I don't see added value in the proposed change. `props.trackPageChanges` is static and never changes during widget's lifetime, there shouldn't be a need to wrap it in `useRef`. For the same reason it is safe to do conditional call and skip unnecessary call of the hook.

2023-02-03 08:42 UTC, r0b1n commented on packages/pluggableWidgets/google-tag-web/src/utils.ts
> +}
Also here. Dojo is either there or not, so the conditional call is always stable.

2023-02-03 09:12 UTC, iobuhov approved these changes

2023-02-10 12:06 UTC, iobuhov approved these changes

2023-02-10 12:27 UTC, leonardomendix approved these changes

2023-02-13 16:19 UTC, merged