[WC-1322]: remove the overflow css property to prevent the render bug
mendix/web-widgets pull request #29
Opened 2022-10-21 13:30 UTC by rahmanunver

## Checklist

-   Contains unit tests ❌
-   Contains breaking changes ❌
-   Contains Atlas changes ❌
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣
-   Did you update version and changelog? ✅ 
-   PR title properly formatted (`[XX-000]: description`)? ✅ ❌

#### Web specific

-   Contains e2e tests ❌
-   Is accessible ❌
-   Compatible with Studio ✅ 
-   Cross-browser compatible ✅ 

## This PR contains

-   [x] Bug fix
-   [ ] Feature
-   [ ] Refactor
-   [ ] Documentation
-   [ ] Other (describe)

## What is the purpose of this PR?

_..._

## Relevant changes

Removed `overflow: hidden` attribute for the element causing the rendering bug.

2022-10-24 14:13 UTC, r0b1n commented on packages/modules/data-widgets/CHANGELOG.md
> +
This should probably go to the changelog of datagrid-web widget. Our release script will place it here from there.

2022-10-24 17:50 UTC, iobuhov approved these changes

2022-11-17 12:49 UTC, iobuhov commented
@rahmanunver, I think we should update changelog and version in `popup-menu-web` and not in `data-widgets`
Alos, you have failing unit tests.

Small note about `data-widgets`: because this is module, we add changlogs rarely to module itself, instead we add chnagelogs to child widgets.

2022-11-17 14:25 UTC, iobuhov approved these changes

2022-11-17 14:25 UTC, iobuhov commented on packages/modules/data-widgets/package.json
> +  "version": "2.5.7",
You don't need to bump version in `data-widgets` as `popup-menu-web` is independent widget and will be published on it's own

2022-11-17 14:25 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/CHANGELOG.md
> +-   We fixed an issue with DataGrid2 where adding a pop-up in a column would cause a rendering bug. (Ticket(s) #165858, #166376, #167745)
I think we don't need to mention DG2. You can just say that we changed widget rendering and now using portal.

2022-11-17 14:25 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/package.json
> +  "version": "3.2.3",
Let's bump minor (3.2.2 => 3.3.0), as this is quite big change.

2022-11-17 14:25 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx
> +        document.body
I think we should create additional container for popup, just div with class `widget-popupmenu-root`

2022-11-17 14:25 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx
>      const ref = useRef<HTMLDivElement>(null);
Please rename `ref` to `triggerRef`

2022-11-17 14:25 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx
>          handleOnClickOutsideElement(ref, () => setVisibility(false));
As I can see right now clicking on menu will cause popup to close as popup is now outside of "trigger". This needs to be fixed. Clicking inside popup should not close it.

2022-12-13 11:00 UTC, iobuhov commented
@rahmanunver, dude, please, rebase your branch.

2022-12-13 11:02 UTC, rahmanunver commented
> @rahmanunver, dude, please, rebase your branch.

Missed it, on it.

2022-12-14 11:30 UTC, iobuhov requested changes
@rahmanunver, need to change few things

2022-12-14 11:30 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx
> +        useHandleOnClickOutsideElement(triggerRef, () => setVisibility(false));
[Hooks cannot be called conditionally](https://reactjs.org/docs/hooks-overview.html#rules-of-hooks)

2022-12-14 11:30 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx
> +    const popupStyles: CSSProperties =
1. Let's create `Menu` component. It will call `useHandleOnClickOutsideElement`.
2. Let's create `useMenuPlacement` and put line 96-112 in it. Also, unit test will be needed for it.

2022-12-14 11:30 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx
> +                  onMouseEnter: handleOnHoverTrigger
Let's use `PointerEnter` here

2022-12-14 11:30 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/utils/document.ts
> +            document.removeEventListener("touchstart", listener);
Please, use `ownerDocument`

2022-12-20 10:04 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/__tests__/Menu.spec.ts
> +describe("Popup menu", () => {
```suggestion
describe("Menu", () => {
```

2022-12-20 10:04 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/__tests__/useMenuPlacement.spec.ts
> +        });
For now this is ok, but in future it's better if we use getBoundClientRect to get offsets

2022-12-20 10:04 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/Menu.tsx
> +    visibility: boolean;
Why we need visibility?

2022-12-20 10:07 UTC, rahmanunver commented on packages/pluggableWidgets/popup-menu-web/src/__tests__/useMenuPlacement.spec.ts
> +        });
The values are being  returned by usePositionObserver hook doesn't only set getBoundClient rect but also makes sure the values are updated with the position of the trigger, didn't want to overrule it so I just mocked that one.

2022-12-20 10:09 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/__tests__/useMenuPlacement.spec.ts
> +        });
Ok

2022-12-20 10:15 UTC, rahmanunver commented on packages/pluggableWidgets/popup-menu-web/src/components/Menu.tsx
> +    visibility: boolean;
Without `visibility` the new `Menu` component doesn't work properly as its `display` property is being set according to parents state (`PopupMenu`) where the trigger logic happens. Do you suggest another way to prevent using `visibility`? 

To sum up, setting the visibility on happens in `PopupMenu`, and hiding it happens in `Menu`, therefore if we assume it's always visible, it'll never hide and remain visible.

2022-12-20 15:36 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/components/Menu.tsx
> +    visibility: boolean;
But then it's up to parent component (PopupMenu) to decide when to show/hide this menu. I would say we should remove visibility prop and add condition in `PopupMenu.tsx`, line 53 to show menu only if visibility is `true`

2022-12-22 09:44 UTC, iobuhov submitted a review, later dismissed
<img src="https://media1.giphy.com/media/13zeE9qQNC5IKk/giphy.gif"/>

2022-12-23 09:41 UTC, iobuhov approved these changes

2023-01-04 09:02 UTC, iobuhov approved these changes

2023-01-04 09:09 UTC, merged