WIP: [WC-1615] Accordion lazy rendering
mendix/web-widgets pull request #292
Opened 2023-01-20 16:38 UTC by iobuhov

### Description

### Pull request type

-   [ ] No code changes (changes to documentation, CI, metadata, etc)
-   [ ] Dependency changes (any modification to dependencies in `package.json`)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Test related change (New E2E test, test automation, etc.)

### What should be covered while testing?

2023-01-25 11:08 UTC, r0b1n approved these changes

2023-01-25 11:11 UTC, tamelbrun requested changes

2023-01-25 11:11 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/MountOnceReady.tsx
> +    isReady.current = isReady.current || ready;
🎄 `isReady.current ||= ready;`

2023-01-25 11:11 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +                        <MountOnceReady ready={!renderCollapsed}>{props.content}</MountOnceReady>
Wouldn't it be easier to simply have a `const renderContent = useRef(false);` here which is `||=`-ed with `!lazyRender || !renderCollapsed`, so you can simply render `renderContent && props.content` instead of a whole separate component?

2023-01-25 12:47 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/components/MountOnceReady.tsx
> +    isReady.current = isReady.current || ready;
Done 🪄

2023-01-25 12:47 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +                        <MountOnceReady ready={!renderCollapsed}>{props.content}</MountOnceReady>
Done 🪄

2023-01-25 12:49 UTC, iobuhov commented
@tamelbrun, please have look one more time 🙏

2023-01-25 14:07 UTC, rahmanunver submitted a review, later dismissed

2023-01-26 15:56 UTC, tamelbrun requested changes

2023-01-26 15:56 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +/* eslint-enable no-unused-vars */
Why do we need to suppress ESLint warnings here?

2023-01-26 15:56 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Why do we need to suppress a warning here?

2023-01-26 15:56 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
On a side note, it would seem that `mapPreviewIconToWebIcon` returns either an object or `undefined`, making the three cases of `?? undefined` below a no-op. If you're touching this code anyway, feel free to clean that up :).

2023-01-26 15:56 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +    renderContent.current ||= !lazyRender || !renderCollapsed;
I think we can do even better: initialize the ref with `loadContent === "always"` and only do `||= !renderCollapsed`. After all, the `loadContent` prop is static.

2023-01-26 15:56 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +    loadContent?: "always" | "whenExpanded";
Why is this prop optional? The prop of the widget isn't (and uses the generated `LoadContentEnum` type).

2023-01-26 15:56 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +                    {renderContent.current ? props.content : null}
Why not simply `renderContent.current && props.content`? This is the recommended syntax for conditional rendering in React if the left side is a boolean.

2023-01-26 16:08 UTC, tamelbrun commented
> P.S. Don't forget to resolve conversations, otherwise I'll never merge it 😂

I'd love to, but I can't :P. According to GitHub's logic, the creator of the pull request or someone with write access to the repository can resolve conversations. And I happen to be neither :).

2023-01-26 16:11 UTC, iobuhov commented
> > P.S. Don't forget to resolve conversations, otherwise I'll never merge it 😂
> 
> I'd love to, but I can't :P. According to GitHub's logic, the creator of the pull request or someone with write access to the repository can resolve conversations. And I happen to be neither :).

Don't you have resolve button 🤨 ???
(I'm asking as probably we need to adjust our repo settings)
![Screen Shot 2023-01-26 at 17 11 16](https://user-images.githubusercontent.com/8282906/214887833-912f08b5-052f-4fb3-91e2-f09342e31663.png)

2023-01-26 16:16 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +/* eslint-enable no-unused-vars */
This is because `eslint` and `typescript-eslint` rules clash. This issue is fixed in #305.
In short, eslint think this is `javascript` and it thinks it's unsed var, for `typescript-eslint` all good

2023-01-26 16:18 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
> Why do we need to suppress a warning here?

Because, we use `hook` in `preview` function (which from eslint point of view is not a component, which is kinda correct, but in our case this function is a functional component` We can't change function name, otherwise export will be broken

2023-01-26 16:19 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +    loadContent?: "always" | "whenExpanded";
Kinda, inheritage from Chak, we were trying to separate components and `ConainerProps`. But, there not a lot of benefit from doing that. I'll do the change

2023-01-26 16:22 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +                    {renderContent.current ? props.content : null}
This my habit from old react days, kinda "best practice". This approach is better then  `&&` in that that it handles `0`. If you say `x` ether `0` or `1`, and you do `{x && "hello"}` user will see `0` on the screen when `x=0`. But in this case we have only `true|false` and react will take care of it. I'll make a change.

2023-01-26 20:42 UTC, iobuhov commented
@tamelbrun, added you as a maintainer 😉 , now you should be able to make resolutions 👍

2023-01-27 14:58 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +/* eslint-enable no-unused-vars */
Alright, just be sure to remove it again when it's no longer necessary ;).

2023-01-27 15:05 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +    loadContent?: "always" | "whenExpanded";
Then the `loadContent = "always"` fallback in the destructuring of the props can also be removed :).

2023-01-27 15:07 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +                    {renderContent.current ? props.content : null}
I would not hesitate to advocate for corporal punishment of anyone who would intentionally use this construct with numbers instead of booleans ;).
✨

2023-01-27 15:08 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +    renderContent.current ||= !lazyRender || !renderCollapsed;
If this was a generic React component, then yes. But the props of a pluggable widget are defined by us, and we _know_ that `loadContent` is a static prop that can only be changed by reconfiguring the widget in Studio Pro. Treating it as "any prop can change" would give the impression that it actualy _could_ change, which is false. But now it's totally fine ✨

2023-01-27 15:14 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx
> +    loadContent?: "always" | "whenExpanded";
Done 🪄

2023-01-27 15:18 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Hmm. Maybe you could use a `PreviewComponent` function internally to make it clear that it actually is a functional component. (I don't know if you can safely substitute `export const preview = PreviewComponent;` for `export function preview(...)`, otherwise you could just `return PreviewComponent(props)`.)

2023-01-27 15:25 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Yes, it will solve the issue, and I think it's more clean way, but then we should fix it in every widget... which is far away from scope of this PR

2023-01-27 15:26 UTC, iobuhov commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Side note, I think once I've tried to do `export const preview = PreviewComponent;`, but AFAIR, it didn't helped, it looks like Studio Pro expects to see `function preview` as statement.

2023-01-30 10:54 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/Accordion.editorPreview.tsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Yeah, I wasn't sure how strict Studio Pro would be. In any case, I'm already happy if we can avoid the ESLint warning :).

2023-01-30 10:58 UTC, tamelbrun commented
@iobuhov One last remark: it looks like there is no test coverage for `loadContent: "whenExpanded"`, all the existing tests were updated to use `"always"`. I would not recommend that ;).

2023-01-30 14:12 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/__tests__/AccordionGroup.spec.tsx
> +    it("keep widgets rendered when 'loadContent' is 'whenExpanded' and 'collapsed' prop became false", () => {
I think you mean `and 'collapsed' prop becomes true`?

2023-01-30 15:01 UTC, tamelbrun commented on packages/pluggableWidgets/accordion-web/src/components/__tests__/AccordionGroup.spec.tsx
> +    it("keep widgets rendered when 'loadContent' is 'whenExpanded' and 'collapsed' prop became false", () => {
✨

2023-01-30 15:02 UTC, tamelbrun approved these changes

2023-01-30 15:34 UTC, merged