Added new pagingOptions=both for datagrid
mendix/web-widgets pull request #342
Opened 2023-02-13 08:18 UTC by irina-ramazova

### Description

Added new PagingOptions to show paging both below and above the grid as it is really necessary feature

### Pull request checklist

-   [ ] All new and existing tests passed
-   [ ] I run `lint` command locally and it doesn’t give errors
-   [ ] PR title properly formatted `[XX-000]: description`
-   [ ] Added record to packages' CHANGELOG.md
-   [ ] Bumped package version in `package.json` and `package.xml`
-   [ ] Added a link to related project PRs (atlas, pluggable-widgets-tools, testProject, etc.) (optional)
-   [ ] Created docs PR to [mendix/docs](https://github.com/mendix/docs.git) and added a link (optional)

### Pull request type

-   [ ] No code changes (changes to documentation, CI, metadata, etc)
-   [ ] Dependency changes (any modification to dependencies in `package.json`)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Test related change (New E2E test, test automation, etc.)

### What should be covered while testing?

-Paging Options

2023-02-20 14:14 UTC, rahmanunver requested changes

2023-02-20 14:14 UTC, rahmanunver commented on packages/pluggableWidgets/datagrid-web/src/components/Table.tsx
> +                    {pagination && (pagingPosition === "top" || pagingPosition === "both")}
This expression will return the right-hand value of the `&&` operator, which will be a `boolean` value rather than the `pagination` component. It must be flipped.

2023-02-20 14:14 UTC, rahmanunver commented on packages/pluggableWidgets/datagrid-web/src/components/Table.tsx
> +                    {pagination && (pagingPosition === "bottom" || pagingPosition === "both")}
Same flip here.

2023-03-01 12:15 UTC, irina-ramazova commented on packages/pluggableWidgets/datagrid-web/src/components/Table.tsx
> +                    {pagination && (pagingPosition === "top" || pagingPosition === "both")}
Fixed into last commit

2023-03-01 12:28 UTC, iobuhov commented
@irina-ramazova, can you please add changelog record?
You can use `pnpm -w changelog` command, package `datagrid-web`

2023-03-01 12:56 UTC, irina-ramazova commented
> 

Im not very know the flow. I shouldchange a changelog-template with my changes. If I run data-widgets\web-widgets\packages\pluggableWidgets\datagrid-web>pnpm -w changelog +> i get an error C:\Users\ramazova\Documents\projects\data-widgets\web-widgets\node_modules\.pnpm\enquirer@2.3.6\node_modules\enquirer\lib\types\array.js:38
      throw new Error('At least one choice must be selectable');

2023-03-01 12:59 UTC, iobuhov commented
Hmmm, this is interesting

2023-03-01 13:20 UTC, irina-ramazova commented
> Alright, never mind, I will add changelog record myself. Thank you for your contribution to web-widgets!

Sorry... Customers asks when it will be released into mendix? Do you have any idea?

2023-03-01 13:42 UTC, iobuhov commented
> > Alright, never mind, I will add changelog record myself. Thank you for your contribution to web-widgets!
> 
> Sorry... Customers asks when it will be released into mendix? Do you have any idea?

Well, shouldn't be a big problem. In theory only thing that left is testing. @leonardomendix, can we test this changes this sprint? Or you busy?

2023-03-01 13:55 UTC, iobuhov commented
@irina-ramazova, I pushed my changes, please `git pull` them

2023-03-01 13:58 UTC, rahmanunver approved these changes

2023-03-01 14:01 UTC, iobuhov approved these changes

2023-03-01 14:05 UTC, leonardomendix commented
> > > Alright, never mind, I will add changelog record myself. Thank you for your contribution to web-widgets!
> > 
> > 
> > Sorry... Customers asks when it will be released into mendix? Do you have any idea?
> 
> Well, shouldn't be a big problem. In theory only thing that left is testing. @leonardomendix, can we test this changes this sprint? Or you busy?

I think so, I can't promise but I can try. 😃

2023-03-03 10:58 UTC, merged

2023-03-03 11:00 UTC, leonardomendix commented
We're good to go! 🚀