DB-1953 remove null check, because null values are a feature in plotly
mendix/web-widgets pull request #42
Opened 2022-11-01 15:15 UTC by JansenNick

## This PR contains

-   [x] Bug fix
-   [x] Feature
-   [ ] Refactor
-   [ ] Documentation
-   [ ] Other (describe)

## What is the purpose of this PR?
Plotly allows for `null` in your data and will by default fill up gaps. It also has the option to set `connectgaps` to false so you can have a line with gaps in between.  https://plotly.com/javascript/line-charts/#connect-gaps-between-data

The code that this pull request removes prevents `null` ending up in your data set, even though plotly can handle this. Right now if you would have an empty value in your dataset the chart would not render. 

By removing this code, the chart will still render when you have an empty value in your data, by default it will connect the gaps and you will have to option to turn this off.

2022-11-01 15:44 UTC, iobuhov commented
@JansenNick, your change cause TypeScript errors, please fix the types and run `pnpm -w run build --filter charts-web` to make sure TS has no complains

2022-11-02 13:23 UTC, iobuhov requested changes

2022-11-02 13:24 UTC, iobuhov commented on packages/shared/charts/src/hooks/usePlotChartDataSeries.ts
> +            yData.push(y.value instanceof Big ? Number(y.value.toString()) : y.value);
cc: @JansenNick

2022-11-02 13:28 UTC, iobuhov approved these changes

2022-11-08 15:54 UTC, rahmanunver approved these changes

2022-11-10 11:34 UTC, merged