[WC-1690]: Dropdown basic UI
mendix/web-widgets pull request #435
Opened 2023-03-08 11:04 UTC by rahmanunver

### Pull request type

Refactoring (e.g. file rename, variable rename, etc.)

New feature (non-breaking change which adds functionality)

---

### Description
The UI part f the Dropdown with single selection functionality. It is inspired from react-select as discussed.

Also split the component a bit to provide more readability, and it still can be re-organised better in the future as the development goes on.

2023-03-09 10:37 UTC, iobuhov requested changes
Let's start preparing widget for publishing. 
- Take time and refactor your code. Remove commented code and inline styling.
- CSS classes should be prefixed with `widget-dropdown`
- Icons should be organaized [same way as in datagrid](https://github.com/mendix/web-widgets/tree/main/packages/pluggableWidgets/datagrid-web/src/components/icons)
- Do we need tests?
- Lst but not lease, @r0b1n, should we move selectors from `src/helpers` to `src/selectors`?
- @takumagott, should we use new icon set? Or we can just hardcode current icons?

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +            }}
Well, this probably good case for a hook I see that we have only two "deps": `inputRef` and `selector`. 
We can move all this callbacks into hook (e.g. `useDownshiftProps(selector, inputRef)`) and inside you can use `useMemo`

But, please, keep in mind that we should try to avoid inline functions in component props. Inline functions should be small, otherwise they become hard to maintain.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +                <div className="widget-dropdown" {...getRootProps({}, { suppressRefError: true })}>
After checking `downshift` docs I see that you have to call [getRootProps](https://github.com/downshift-js/downshift/blob/c6c0af5ef4655edbddbfa0ae153633bfd5e7d6af/README.md#getrootprops) only if you have [custom layout](https://github.com/downshift-js/downshift/blob/c6c0af5ef4655edbddbfa0ae153633bfd5e7d6af/docusaurus/pages/combobox.js).

Which is not our case. So, please remove them as we probably don't need it.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +                        style={{ border: isOpen ? "1px solid #264ae5" : undefined }}
Inline styles. This should be classes `active/open` or with other name

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +                        />
Why we have to put input inside our our `toggleButton`?
Do we need `toggleButton` at all? Maybe we can just use surrounding div for styling and we don't need to call `getToggleButtonProps`

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +                                    </svg>
1. Please, move icons to `src/assets/icons.tsx`
2. Why we use named colors (black, gray)?  This should be part of `scss` and they probably should be in variable. As this also should be configured by theme.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +        <div>
Why we need this div?

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +                    <DropdownMenu
Should we use portal?

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +                }}
Please, change inline style to classes. Use `classNames` helper.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/ui/Dropdown.scss
> +}
Let's not do same mistake as we did with other widgets. We need to use "module name" in front of any class name (e.g. `widget-dropdown-menu` or `widget-dropdown-item`).
This will prevent css rule clashes and simplify future changes.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/ui/Dropdown.scss
> +}
Probably we need more clear class name, not just utility class.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/ui/Dropdown.scss
> +}
Please, don't override styles for atlas. If you need apply display flex, create separate class with bigger wight that will override `display` property.

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/helpers/Association/AssociationOptionsProvider.ts
>      }
Why we removing search?

2023-03-09 10:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +                                      color: selectedItem === item ? "white" : "black"
1. Please, don't use CSS color names.
2. Save all colors to sass variables.
3. Give this variables meaningful name

2023-03-10 08:42 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
@iobuhov the suggested change unnecessary calls `getSelector` every render. This effectively creates a new selector object and then throws it away.

2023-03-10 09:06 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/helpers/Association/AssociationOptionsProvider.ts
>      }
This was just an experiment, it it not part of the basic implementation. We don't plan to include lazy loading and/or partial fetch of objects in this initial version. This effectively means we have all objects from data source in our hands, and can filter in memory. In the next version we will address search and partial loading.

2023-03-10 09:11 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
Ah ,yes, you right, but then should we use `useState`?
Like:
```
const [selector] = useState(() => getSelector(props));
```

2023-03-10 09:14 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
cc: @r0b1n

2023-03-10 10:53 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
I don't think we need state for this, it never changes. What was wrong with the initial implementation?

2023-03-10 11:04 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
well, I though 1 line with `useState` is bit more compact and easy to read. + non-null assertion (`.current!`) bit triggered me

2023-03-10 11:06 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/helpers/Association/AssociationOptionsProvider.ts
>      }
Ah, ok, got it

2023-03-10 13:41 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
We could move it out to a custom hook, and possible make it look like:
```
    const selectorRef = useRef<SingleSelector | undefined>(undefined);
    if (!selectorRef.current) {
        selectorRef.current = getSelector(props);
    } else {
        selectorRef.current.updateProps(props);
    }
    const selector = selectorRef.current!;
```

2023-03-22 17:42 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
Can we move this to the `useGetSelector`?

2023-03-22 17:47 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/__tests__/__snapshots__/Dropdown.spec.tsx.snap
> +  "debug": [Function],
This looks like something we don't want to include in the snapshot. We are probably checking too much.

2023-03-23 07:28 UTC, luisarthurmicainunes commented on packages/pluggableWidgets/dropdown-web/src/__tests__/__snapshots__/Dropdown.spec.tsx.snap
> +              class="widget-dropdown-clear-button"
Aren't you on holidays, Illia? :)

2023-03-23 12:33 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
Do you mean the `updateProps` part? We can actually.

2023-03-23 12:36 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/__tests__/__snapshots__/Dropdown.spec.tsx.snap
> +  "debug": [Function],
Yes, for snapshot I should've used `component.container` rather than just `component`

2023-03-23 13:19 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/__tests__/__snapshots__/Dropdown.spec.tsx.snap
> +              class="widget-dropdown-clear-button"
Indeed it's a mistake. Fixed now.

2023-03-23 13:19 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/__tests__/__snapshots__/Dropdown.spec.tsx.snap
> +  "debug": [Function],
Done

2023-03-23 13:19 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
Done

2023-03-23 13:19 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +            }}
Done

2023-03-23 13:19 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    selector.updateProps(props);
Done

2023-03-23 13:20 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +                        />
The properties for toggling comes from these props, so we're keeping them in discussion with @iobuhov

2023-03-24 09:22 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/__tests__/__snapshots__/Dropdown.spec.tsx.snap
> +              class="widget-dropdown-clear-button"
😂 🙈 , it's not me, it's my AI guard.

2023-03-29 12:06 UTC, closed without merging