[WC-1699] Selection helper widget
mendix/web-widgets pull request #439
Opened 2023-03-09 15:52 UTC by r0b1n

### Pull request type

New feature (non-breaking change which adds functionality)

---

### Description

- Add selection context to PW commons.
- Provide selection context to header widgets in Gallery widget
- Add Selection Helper widget that could be placed in the header of gallery

### What should be covered while testing?

- Selection Helper widget works with Gallery widget. 
- Gallery widget allows place widget Selection Helper when Multi selection is enabled (header is shown while no sorting and filtering are enabled)
- Filtering and sorting widgets still work

2023-03-10 12:30 UTC, iobuhov commented on packages/pluggableWidgets/selection-helper-web/prettier.config.js
> +};
You on purpose use base from PWT?
I would recommend use our current config that we use for other widgets
```sh
pnpm add -D "@mendix/prettier-config-web-widgets@*"
```

```js
module.exports = require("@mendix/prettier-config-web-widgets");
```

2023-03-10 12:30 UTC, iobuhov commented on packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.editorConfig.ts
> +// }
Why is this commented?

2023-03-10 12:30 UTC, iobuhov commented on packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.editorConfig.ts
> +    defaultProperties: Properties /* , target: Platform*/
Let's remove commented arg

2023-03-10 12:30 UTC, iobuhov commented on packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.editorPreview.tsx
> +}
Ah, okay, there is WIP

2023-03-10 12:30 UTC, iobuhov commented on packages/pluggableWidgets/selection-helper-web/src/components/CheckBox.tsx
> +}
Nice solution!

2023-03-13 11:42 UTC, r0b1n commented on packages/pluggableWidgets/selection-helper-web/src/components/CheckBox.tsx
> +interface CheckBoxProps {
We don't pass anything really meaningful at the moment, I don't think this is needed at the moment

2023-03-14 14:04 UTC, iobuhov requested changes

2023-03-14 14:04 UTC, iobuhov commented on packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.xml
> +    <description>My widget description</description>
I think we need a better description 😂

2023-03-14 14:14 UTC, iobuhov submitted a review, later dismissed

2023-03-14 16:37 UTC, iobuhov approved these changes

2023-03-15 08:45 UTC, leonardomendix approved these changes

2023-03-15 08:48 UTC, merged