[WC-1296]: Dropdown basic (Single selection)
mendix/web-widgets pull request #472
Opened 2023-03-28 11:43 UTC by rahmanunver

### Pull request type

New feature (non-breaking change which adds functionality)

---

### Description

Basic UI for Dropdown single selection. Includes some unit tests and icons already.

### What should be covered while testing?
Basic behavior for single selection, select and removing an option, search through the input etc.

2023-03-28 11:57 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/Dropdown.editorPreview.tsx
> +};
This file needs some attention. Remove ts-ignore and commented out code, make sure design preview works.

2023-03-28 11:59 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/Dropdown.xml
> +    <helpUrl>https://docs.mendix.com/appstore/widgets/dropdown</helpUrl>
This link could be added in Readme file as well

2023-03-29 07:46 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +/* eslint-disable react/jsx-key */
We need to fix the code instead of disabling the rule

2023-03-31 08:17 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +                              }
Let's create CSS classes for those states instead of hard-coding background colors.

2023-03-31 08:19 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/helpers/Association/AssociationOptionsProvider.ts
> +        // const items = props.ds.items ?? [];
Let's remove comments

2023-04-03 13:05 UTC, rahmanunver commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +                              }
Changed this, thanks!

2023-04-05 08:41 UTC, r0b1n submitted a review, later dismissed

2023-04-18 16:07 UTC, r0b1n commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownPreview.tsx
> +                        style={{ backgroundColor }}
Looking at this code, I have a question how do we handle and render disabled/readonly state of the actual dropdown on pages? If we have a special CSS class for disabled state we could re-use it here as well.

2023-04-21 09:36 UTC, iobuhov requested changes
Just few minor things. Main thing -- please check Roman's comment, we need to handle disabled state.

2023-04-21 09:36 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +            className={classNames("widget-dropdown-menu", { hidden: !isOpen })}
NIT: Can we prefix this class? Like `widget-dropdown-menu-hiddne`?

2023-04-21 09:36 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownPreview.tsx
> +                        style={{ backgroundColor }}
+1

2023-04-21 09:36 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Placeholder.tsx
> +            <div className="widget-dropdown-placeholder form-control">&nbsp;</div>
Nice one! 😄

2023-04-21 09:37 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +            className={classNames("widget-dropdown-menu", { hidden: !isOpen })}
NIT: I see we have more classes, like selected and other. They probably also should be prefixed.

2023-04-21 14:48 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownMenu.tsx
> +            className={classNames("widget-dropdown-menu", { hidden: !isOpen })}
No, I mean do like in BEM, but with just hypens.
So, it's fine to have two classes. One is "Block name" and second is "Block modifier". In bem it probably would be:
```css
.widget-dropdown-menu.widget-dropdown-menu--hidden {}
```
But because we don't use BEM. We probably we just create long classes
```css
.widget-dropdown-menu.widget-dropdown-menu-hidden {}
```

2023-04-26 07:22 UTC, iobuhov requested changes

2023-04-26 07:22 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/Dropdown.tsx
> +    console.log("readOnly", props);
Logs 🙃

2023-04-26 07:25 UTC, iobuhov commented on packages/pluggableWidgets/dropdown-web/src/components/DropdownPreview.tsx
> +                        style={{ backgroundColor }}
Lat's back to this discussion on v2

2023-04-26 08:22 UTC, iobuhov approved these changes

2023-04-26 12:57 UTC, iobuhov submitted a review, later dismissed

2023-04-28 08:10 UTC, r0b1n approved these changes

2023-04-28 08:11 UTC, merged