Add new workflow to add a first comment on fork PRs
mendix/web-widgets pull request #483
Opened 2023-04-03 13:22 UTC by leonardomendix

### Pull request type

No code changes (changes to documentation, CI, metadata, etc.)

---

### Description

Add a new workflow to add a first welcome comment on fork PRs. Using the last comment from Illia as inspiration. 💐

2023-04-03 13:51 UTC, rahmanunver submitted a review, later dismissed

2023-04-03 14:42 UTC, iobuhov requested changes
Can we wait a bit 😬 ?
I have feeling that some of sentences may not apply to new PRs, so, I want to propose some changes. BTW, actions is looking good 👍

2023-05-15 07:47 UTC, iobuhov approved these changes

2023-05-15 07:48 UTC, closed without merging

2023-05-15 08:24 UTC, takumagott approved these changes
LGTM 👍