[WC-1624] Rename internal packages
mendix/web-widgets pull request #499
Opened 2023-04-28 13:36 UTC by samuelreichert

### Pull request type

Refactoring (e.g. file rename, variable rename, etc.)

---

### Description

Renaming all pluggableWidgets, customWidgets and modules to be under `@mendix/`.

2023-05-02 09:40 UTC, iobuhov requested changes

2023-05-02 13:43 UTC, samuelreichert commented on automation/run-e2e/lib/update-test-project.mjs
> +        `--filter ${pkgName}`
Oh, I thought that this would look for the project folder, which does not have the `@mendix/` prefix..
I will remove that

2023-05-03 10:52 UTC, iobuhov approved these changes
LGTM

2023-05-03 11:28 UTC, r0b1n approved these changes

2023-05-03 14:42 UTC, merged