[WC-1820] Fix regression filter regression introduced in data-widgets 2.7.1
mendix/web-widgets pull request #503
Opened 2023-05-04 14:32 UTC by iobuhov

### Pull request type

Bug fix (non-breaking change which fixes an issue)

---

### Description
As a result of refactoring and fixing filter value initialization we missed call that sets initial datasource condition. This PR bring this call(s) back.

2023-06-13 09:58 UTC, rahmanunver commented on packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/FilterComponent.tsx
> +function useSetInitialConditionEffect(
There are two methods with same name, they have different logics but naming is a bit confusing.

2023-06-13 10:14 UTC, rahmanunver commented on packages/pluggableWidgets/datagrid-dropdown-filter-web/src/features/setup.ts
> +        : [{ caption: props.emptyOptionCaption ?? "", value: EMPTY_OPTION_VALUE }, ...options];
Why do we return the `...options` too in case `multiSelect` is `false`?

2023-06-13 10:25 UTC, rahmanunver requested changes
Added some comments and questions with @samuelreichert , great work 🕺

2023-06-13 11:36 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-number-filter-web/cypress/integration/DataGridNumberFilter.spec.js
> +        it.skip("compares with a screenshot baseline and checks if all datagrid and filter elements are rendered as expected", () => {
Just forgot to remove

2023-06-13 11:41 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/FilterComponent.tsx
> +function useSetInitialConditionEffect(
Yeah, it's bit confusing, but this is the idea - each package has it's own `usetSetInitialConditionEffect`.
For now it's how we fit the issue.

2023-06-13 15:44 UTC, rahmanunver submitted a review, later dismissed

2023-06-20 07:47 UTC, leonardomendix approved these changes

2023-06-21 08:06 UTC, gjulivan approved these changes

2023-06-21 08:26 UTC, merged