[WC-1349] virtual scroll issue - bump widgets version
mendix/web-widgets pull request #535
Opened 2023-05-24 13:35 UTC by gjulivan

Bump version of affected widget in virtual scrolling issue

2023-05-24 13:43 UTC, iobuhov requested changes
What the reason for removing changelogs?

2023-05-24 13:43 UTC, iobuhov commented on packages/modules/data-widgets/CHANGELOG.md
> -
Is this necessary?

2023-05-24 13:45 UTC, gjulivan commented on packages/modules/data-widgets/CHANGELOG.md
> -
it was removed because unecessary ?

2023-05-24 13:47 UTC, iobuhov approved these changes
LGTM

2023-05-24 13:48 UTC, leonardomendix approved these changes

2023-05-25 12:09 UTC, leonardomendix approved these changes

2023-05-25 12:49 UTC, rahmanunver approved these changes

2023-05-25 12:59 UTC, merged