feat: [WC-1832] - update icons
mendix/web-widgets pull request #585
Opened 2023-06-12 07:01 UTC by gjulivan

### Pull request type

---

### Description

2023-06-15 12:51 UTC, iobuhov requested changes
Please, keep icons in xml and bump package versions, if needed.

2023-06-15 12:51 UTC, iobuhov commented on packages/customWidgets/calendar-web/src/Calendar.xml
Let's not remove this one as it still probably used in Mx8

2023-06-16 08:26 UTC, iobuhov commented
Tested. Works as expected.

2023-06-16 08:27 UTC, iobuhov commented
@leonardomendix, can I get approval? 😄

2023-06-16 09:39 UTC, leonardomendix approved these changes

2023-06-16 09:42 UTC, merged