fix: pop up menu
mendix/web-widgets pull request #593
Opened 2023-06-20 14:52 UTC by gjulivan

Fix pop up menu changelog and versioning.
Fix z-index on datagrid filter causing popup menu showing on top of the filter while the filter in sticky position.

related to [WC-1125] and [WC-1705]
and related PR: https://github.com/mendix/web-widgets/pull/545/

[WC-1125]: https://mendix.atlassian.net/browse/WC-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WC-1705]: https://mendix.atlassian.net/browse/WC-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-21 07:17 UTC, iobuhov commented
E2E failed because
```
Error: [@mendix/popup-menu-web] package.json and package.xml versions do not match.
```

2023-06-21 07:41 UTC, iobuhov approved these changes

2023-06-21 07:43 UTC, iobuhov requested changes

2023-06-21 07:43 UTC, iobuhov commented on packages/modules/data-widgets/CHANGELOG.md
>  -   We removed dead span styling from module SCSS
```suggestion
### Fixed

-   We fixed popup menu showing on top of datagrid filter in sticky position.

-   We removed dead span styling from module SCSS
```

four hash (####) sction is for "nested" widgets
three hash (###) section is for "data-widgets" changes

2023-06-21 08:29 UTC, iobuhov approved these changes

2023-06-21 08:50 UTC, samuelreichert approved these changes
LGTM

2023-06-22 07:49 UTC, r0b1n commented on packages/pluggableWidgets/popup-menu-web/CHANGELOG.md
> +-   We fixed an issue causing popup menu to appear behind other elements(modal popups). This fix will move popupmenu-menu wrapper DOM in the same level as the trigger button. Thus, custom styling tar
Suggested:
```
We have addressed an issue that was causing the popup menu to appear behind other elements, such as modal popups. This fix involved modifying the DOM structure by moving the `popupmenu-menu` element to the same level as the trigger button. As a result, custom styling that targets the popup menu may have been affected.
```

2023-06-22 08:35 UTC, iobuhov commented on packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss
> +        > * {
Risky, but I happy that we fix this selector.

2023-06-22 08:36 UTC, iobuhov commented on packages/pluggableWidgets/popup-menu-web/src/ui/PopupMenu.scss
> +.table .td > .popupmenu {
This is bit overkill, now we have styles that depends on other widgets. Is there other way to fix it?

2023-06-27 13:22 UTC, leonardomendix approved these changes

2023-06-27 14:42 UTC, iobuhov approved these changes
LGTM

2023-06-28 07:57 UTC, merged