[WC-1585]: tooltip not showing when its close to table head
mendix/web-widgets pull request #630
Opened 2023-07-25 12:56 UTC by samuelreichert

### Pull request type

Bug fix (non-breaking change which fixes an issue)

---

### Description
When a tooltip was positioned to top inside a datagrid table it was not showing completely, because the table header was positioned in front of it.

2023-07-25 13:21 UTC, iobuhov requested changes
1. Version bump
2. Changelogs
Thank you

2023-07-26 08:00 UTC, iobuhov submitted a review, later dismissed

2023-07-27 11:57 UTC, iobuhov approved these changes

2023-07-27 14:23 UTC, leonardomendix approved these changes

2023-07-28 07:58 UTC, gjulivan approved these changes

2023-07-28 09:02 UTC, merged