fix(video-player): youtube video not mute on load
mendix/web-widgets pull request #643
Opened 2023-08-03 16:40 UTC by gjulivan

### Pull request type

Bug fix: Youtube video cannot mute on first load if the setting is set to Mute.

### Description

youtube video has different parameters for mute on load,
previously it was "muted=1", changed to "mute=1"

2023-08-04 07:01 UTC, r0b1n requested changes

2023-08-04 07:41 UTC, samuelreichert approved these changes

2023-08-04 07:44 UTC, gjulivan commented on packages/pluggableWidgets/video-player-web/CHANGELOG.md
> +-   We fixed the issue where youtube video cannot mute on first load.
fixed

2023-08-04 10:00 UTC, r0b1n approved these changes

2023-08-07 09:52 UTC, leonardomendix approved these changes

2023-08-07 15:22 UTC, merged