fix: combobox styling
mendix/web-widgets pull request #674
Opened 2023-08-24 00:53 UTC by gjulivan

### Pull request type

---

### Description

2023-08-24 07:40 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    "widget-combobox-down-arrow-icon-rotated": isOpen
Why we need icon rotated?

2023-08-24 07:41 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx
> +import { Checkbox } from "src/assets/icons";
Unit tests will fail if you don't use relative path

2023-08-24 19:06 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    "widget-combobox-down-arrow-icon-rotated": isOpen
to allow dropdown and up arrow when open

2023-08-25 08:51 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span>
I'm just curious how this supposed to work? 😕

2023-08-25 08:52 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    "widget-combobox-down-arrow-icon-rotated": isOpen
Is this discussed with Ana? I'm not sure about this change though.

2023-08-25 08:59 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span>
by removing the SVG and adding custom fonts to the span.

2023-08-25 09:01 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    "widget-combobox-down-arrow-icon-rotated": isOpen
i think it is a standard behavior?
down arrow will become up arrow (with animation) once combo box drop down is open.

i've show this behavior as well to ana.

2023-08-25 11:58 UTC, samuelreichert submitted a review, later dismissed

2023-08-25 12:52 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    <rect x="2" width="20" height="20" rx="5" fill="#264AE5" />
Can we make those colors configurable via CSS?

2023-08-28 07:36 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    <rect x="2" width="20" height="20" rx="5" fill="#264AE5" />
yes. fixed.

2023-08-28 13:13 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    "widget-combobox-down-arrow-icon-rotated": isOpen
We have many dropdowns (core, datagrid) and non of this include icon animation. I think we trying to match atlas styling and by default it has no animation.

2023-08-28 13:13 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +                    "widget-combobox-down-arrow-icon-rotated": isOpen
I think, as this is for internal review, let's skip this animation for now. I think we should ask Anna first, as she is working hard on Atlas right now, and I think we should be consistent on details.

2023-08-28 14:28 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
> +        }
```suggestion
        &:not(.checked) rect {
            stroke: #ced0d3;
        }
```

2023-08-28 14:36 UTC, iobuhov requested changes

2023-08-28 14:36 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
> +            fill: currentColor;
We need remove this line to avoid black triangle on icon in "checked" state.

2023-08-28 14:36 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx
> +                                )}
Let's remove useless `input` element.

2023-08-28 14:36 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span className="icon-container">
Class name please.

2023-08-28 14:37 UTC, iobuhov commented
Beside my main let's also add `text-overflow: ellipsis` for items with long names. To avoid such cases:
![image](https://github.com/mendix/web-widgets/assets/8282906/ab13e7fd-1638-4f19-96fd-b392f8265581)

2023-08-28 23:45 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
> +        }
fixed

2023-08-28 23:45 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
> +            fill: currentColor;
fixed

2023-08-28 23:45 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx
> +                                )}
fixed

2023-08-28 23:46 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span className="icon-container">
fixed

2023-08-28 23:47 UTC, gjulivan commented
> Beside my main let's also add `text-overflow: ellipsis` for items with long names. To avoid such cases: ![image](https://user-images.githubusercontent.com/8282906/263735467-ab13e7fd-1638-4f19-96fd-b392f8265581.png)

it will be on the scope for WC-2022

2023-08-29 11:18 UTC, leonardomendix approved these changes

2023-08-29 11:20 UTC, merged