Wc 2022 combobox internal release finalize
mendix/web-widgets pull request #679
Opened 2023-08-30 08:28 UTC by gjulivan

### Pull request type

---

### Description

2023-09-01 07:26 UTC, iobuhov commented
@gjulivan , please, don't forget to add add PR type and description.

2023-09-01 07:37 UTC, iobuhov requested changes

2023-09-01 07:37 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span className="widget-combobox-icon-container" role="checkbox">
Why do we need this role? How this improve a11y?

2023-09-01 07:37 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
> +        .text {
Please, keep prefixes, we should be consistent with class names. Class prefix `widget-combobox-`

2023-09-01 07:37 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
> +            &.boxes {
Class prefix `widget-combobox-`

2023-09-01 07:37 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationSimpleCaptionsProvider.tsx
> +        return <span className="text">{this.get(value)}</span>;
Class prefix `widget-combobox-`

2023-09-01 07:37 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx
> +                <div className={classNames("widget-combobox-selected-items", selector.selectedItemsStyle)}>
Class prefix `widget-combobox-`

2023-09-01 07:37 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx
> +                            {...{ ...getInputProps() }}
Double destructuring

2023-09-04 07:06 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +                    <caption>No Item text</caption>
Danny always reiminds us to keep only first letter in capital. So, let's change to "No item text"

2023-09-04 07:10 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
>      return (
I noticed it only right now, but why DOM structure in SingleMenu and MultiMenu is different?

2023-09-05 07:34 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span className="widget-combobox-icon-container" role="checkbox">
yes

2023-09-05 07:35 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +        <span className="widget-combobox-icon-container" role="checkbox">
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role

2023-09-06 08:50 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +// import { Icon } from "mendix/components/web/Icon";
Please, remove comment

2023-09-06 22:02 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +// import { Icon } from "mendix/components/web/Icon";
removed

2023-09-07 07:35 UTC, iobuhov submitted a review, later dismissed

2023-09-07 07:47 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx
> +                        placeholder=" "
Is hardcoded space as expected?

2023-09-07 07:50 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx
> +    placeholderText?: string | null;
In which case we need `null` and in which case it is optional?

2023-09-07 07:56 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx
> +interface SingleSelectionProps extends SelectionBaseProps {
Pass a generic to `SelectionBaseProps` instead of re-defining the `selector` field.

2023-09-07 08:07 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +                </li>
I like that we extracted top level component, maybe we can abstract away menu items as well.

2023-09-07 08:15 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +interface ComboboxMenuProps extends Partial<UseComboboxPropGetters<any>> {
I guess it should be `string` instead of `any`.

2023-09-07 08:25 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +            {items.map((item, index) => (
Why do we need to render items if menu is closed?

2023-09-07 09:12 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx
> +                {isOpen ? isEmpty ? <EmptyItemPlaceholder>{placeholderText}</EmptyItemPlaceholder> : children : null}
Looking at the code, this is not "placeholder text", but "no options available text".

2023-09-07 09:13 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/Placeholder.tsx
> +}
This should also use "no options" instead of "empty item" in its name and CSS classes.

2023-09-07 09:19 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx
> +                        placeholder=" "
Yes, due to the use of css :placeholder-shown

2023-09-07 11:32 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +            {items.map((item, index) => (
this is part of best practice from downshift. i guess they want to keep the reference set up from getMenuProps

2023-09-07 11:46 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +            {items.map((item, index) => (
Could you point to their documentation or examples regarding this topic?

2023-09-07 11:53 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx
> +export function ComboboxMenuWrapper(props: ComboboxMenuWrapperProps): ReactElement {
fixed

2023-09-07 11:53 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx
> +interface SingleSelectionProps extends SelectionBaseProps {
fixed

2023-09-07 11:53 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +interface ComboboxMenuProps extends Partial<UseComboboxPropGetters<any>> {
fixed

2023-09-07 11:53 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +                <property key="noItemText" type="textTemplate" required="false">
fixed

2023-09-07 11:53 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx
> +                {isOpen ? isEmpty ? <EmptyItemPlaceholder>{placeholderText}</EmptyItemPlaceholder> : children : null}
fixed

2023-09-07 11:53 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/Placeholder.tsx
> +}
fixed

2023-09-07 11:54 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +            {items.map((item, index) => (
I see that they render a menu wrapper regardless of the `isOpen` which we also do, that is fine. But I see that they are not rendering items if `isOpen` is `false`, and my question is about those, not the wrapper.

2023-09-07 12:08 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/helpers/types.ts
> +export type SelectionType = SingleSelector | MultiSelector;
I suggest the following naming:
```
export type SelectionType = "single" | "multi";
export type Selector = SingleSelector | MultiSelector;
```

2023-09-07 12:10 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/helpers/types.ts
>      readOnly: boolean;
Generic param named `SelectorType` obscures `SelectorType` type from outside, I suggest sticking with one letter naming `SelectorBase<T, V> {` - `T` for selection type, `V` for value type.

2023-09-07 12:22 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/helpers/types.ts
> +export type SelectionType = SingleSelector | MultiSelector;
Also, some other places use explicitly `SingleSelector | MultiSelector`, please replace it with newly created joined type.

2023-09-07 20:21 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +            {items.map((item, index) => (
children component already not rendered if isOpen is false. 
nevertheless, i will add constraint in here as well.

2023-09-07 20:49 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx
> +                </li>
added

2023-09-07 20:49 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/helpers/types.ts
> +export type SelectionType = SingleSelector | MultiSelector;
fixed

2023-09-07 20:49 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/helpers/types.ts
>      readOnly: boolean;
fixed

2023-09-08 07:40 UTC, iobuhov approved these changes
LGTM

2023-09-08 11:19 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxOptionWrapper.tsx
> +interface ComboboxOptionWrapperProps extends PropsWithChildren, Partial<UseComboboxPropGetters<any>> {
It shouldn't be `any`.

2023-09-08 11:20 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxOptionWrapper.tsx
> +interface ComboboxOptionWrapperProps extends PropsWithChildren, Partial<UseComboboxPropGetters<any>> {
In other places as well

2023-09-11 05:44 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxOptionWrapper.tsx
> +interface ComboboxOptionWrapperProps extends PropsWithChildren, Partial<UseComboboxPropGetters<any>> {
fixed

2023-09-11 06:01 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx
> +                            <Checkbox checked={selector.currentValue?.includes(item)} />
isSelected could be reused here

2023-09-11 07:40 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx
> +                            <Checkbox checked={selector.currentValue?.includes(item)} />
fixed

2023-09-11 07:48 UTC, r0b1n commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxOptionWrapper.tsx
> +interface ComboboxOptionWrapperProps extends PropsWithChildren, Partial<UseComboboxPropGetters<any>> {
Please get rid of `any` in other places of the widget as well. Search in the `combobox-web` folder for `any` still gives hits.

2023-09-11 07:52 UTC, iobuhov approved these changes

2023-09-11 08:14 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/components/ComboboxOptionWrapper.tsx
> +interface ComboboxOptionWrapperProps extends PropsWithChildren, Partial<UseComboboxPropGetters<any>> {
fixed, 
i leave this one :
` getToggleButtonProps: (options?: UseComboboxGetToggleButtonPropsOptions | undefined) => any;`
because the return value really could be anything. no type https://github.com/downshift-js/downshift/blob/master/src/hooks/useCombobox/index.js

2023-09-11 08:16 UTC, iobuhov approved these changes

2023-09-11 08:17 UTC, r0b1n approved these changes

2023-09-11 08:27 UTC, merged