[WC-2023] Implement disabled state on DG2 export
mendix/web-widgets pull request #768
Opened 2023-10-17 14:23 UTC by samuelreichert

### Pull request type

New feature (non-breaking change which adds functionality)

---

### Description
- Create a modal to disable any interaction with DataGrid2 while exporting
- Provide a progress bar with percentage of completion when total count is available
- Provide an indeterminate progress bar when no total count is available
- Provide a visual way to abort the exporting

2023-10-18 12:33 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/typings/global.d.ts
> +        __abort: () => void;
I'm not sure that defining this function on window is needed. If you wan to make it available you should probably define it on some "scope" not directly on window

2023-10-20 08:38 UTC, iobuhov requested changes

2023-10-20 08:38 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/components/ProgressModal.tsx
> +    const [isModalOpen, setIsModalOpen] = useState(false);
If you accept state (`props.open`) from props, then you don't need "internal" state. Always choose only one thing: ether - your component is "controlled" and then it don't have any state and always depends on props or - your component "uncontrolled" and it maintain it's own internal state.

2023-10-20 08:38 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/components/WidgetRoot.tsx
> +            style={{ position: "relative" }}
Please, don't use inline styles. Inline styles very hard to override. If you need set position, use `_datagrids.scss`

2023-10-20 08:45 UTC, iobuhov requested changes

2023-10-20 08:45 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx
> +            onDialogClose={abort}
Let's rename `onDialogClose` to `onExportCancel`

2023-10-23 13:51 UTC, iobuhov approved these changes

2023-10-23 14:00 UTC, iobuhov submitted a review, later dismissed

2023-10-24 08:46 UTC, iobuhov submitted a review, later dismissed

2023-10-26 10:02 UTC, iobuhov approved these changes

2023-10-27 12:31 UTC, leonardomendix approved these changes

2023-10-27 12:33 UTC, merged