[WC-2151]: Combobox screenreader a11y (Multi-selection)
mendix/web-widgets pull request #774
Opened 2023-10-20 13:04 UTC by rahmanunver

### Pull request type

Breaking change (fix or feature that would cause existing functionality to change)

---

### Description
Override the default screen reader `getA11yStatusMessage` method inside Downshift to include the selected items in announcement when reading the Multi selection combobox. 

Also, due to this being a part of focusing on Multi selection, we noticed there is a mismatch in behaviour with Single and Multi selection; 
Single selection doesn't open menu when tab focused, but does when click focused. (_correct behaviour_)
Mutli selection did open menu both when tab and click focused, so aligned it with Single now.

### What should be covered while testing?
Focusing on Multi selection both with tab and click, using screenreader utilities and make sure we get the selected values announced. Also, multi selection changed behaviour in terms of focusing, it doesn't open the dropdown anymore on Tab focus.

2023-10-20 13:26 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
> +            },
I'm bit concerned, how we going to translate this messsage?

2023-10-20 13:33 UTC, rahmanunver commented on packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
> +            },
Not sure either, I think we didn't handle that at all, will check if downshift is doing anything there

2023-10-23 07:44 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
> +                    message += "No results are available.";
isn't this should use empty item message?

2023-10-23 08:43 UTC, rahmanunver commented on packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
> +                    message += "No results are available.";
Do you mean emptyOptionsText? This is announced when there's no search result onChange of the combobox input, wasn't empty item message

2023-10-24 13:17 UTC, gjulivan approved these changes

2023-10-25 14:48 UTC, gjulivan submitted a review, later dismissed

2023-10-27 09:27 UTC, iobuhov requested changes

2023-10-27 09:27 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +                <property key="i18nInstructions" type="string" defaultValue="Use up and down arrow keys to navigate. Press Enter or Space Bar keys to select." required="true">
Can we change type to `textTempalte`?
We can have default values using `translations` tag (for en_US)

2023-10-27 09:27 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +                <property key="i18nInstructions" type="string" defaultValue="Use up and down arrow keys to navigate. Press Enter or Space Bar keys to select." required="true">
NIT: i18n - stands from "internationalization", I more correct is to use a11y. As this props about a11y and not i18n

2023-10-27 09:27 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
> +                }
Yeah, looks much better!

2023-10-27 09:27 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
> +                console.log(message);
Remove log.

2023-10-27 10:45 UTC, rahmanunver commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +                <property key="i18nInstructions" type="string" defaultValue="Use up and down arrow keys to navigate. Press Enter or Space Bar keys to select." required="true">
We can yeah, but what would be the benefit?

2023-10-27 10:53 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +                <property key="i18nInstructions" type="string" defaultValue="Use up and down arrow keys to navigate. Press Enter or Space Bar keys to select." required="true">
Main benefits are:
1. Developer can use template expression
2. Text template require template for each language configured in SP. So, this will make sure this labels get translated translation for other languages.

2023-10-30 07:48 UTC, samuelreichert reviewed
Hey, is it expected to have these missing dependencies on `packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftSingleSelectProps.ts`? (a11yStatusMessage.a11yInstructions, ...)

2023-10-30 07:48 UTC, samuelreichert commented on packages/pluggableWidgets/combobox-web/src/Combobox.xml
> +            <propertyGroup caption="Accesibility Status Message ">
```suggestion
            <propertyGroup caption="Accessibility Status Message ">
```

2023-10-31 10:53 UTC, samuelreichert submitted a review, later dismissed

2023-10-31 12:38 UTC, samuelreichert approved these changes

2023-10-31 14:05 UTC, iobuhov submitted a review, later dismissed
LGTM 👍

2023-11-20 08:33 UTC, gjulivan approved these changes

2023-11-20 14:20 UTC, merged