fix: change checkbox to use input tag
mendix/web-widgets pull request #788
Opened 2023-10-26 23:07 UTC by gjulivan

### Pull request type

---

### Description

2023-10-27 09:09 UTC, iobuhov requested changes

2023-10-27 09:09 UTC, iobuhov commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +            <input type="checkbox" tabIndex={-1} checked={checked} id={id} />
Small detail about a11y: let's add `role=presentation` attribute.

2023-10-27 09:55 UTC, gjulivan commented on packages/pluggableWidgets/combobox-web/src/assets/icons.tsx
> +            <input type="checkbox" tabIndex={-1} checked={checked} id={id} />
fixed

2023-10-27 10:13 UTC, iobuhov submitted a review, later dismissed

2023-10-31 10:33 UTC, iobuhov approved these changes

2023-10-31 11:48 UTC, rahmanunver approved these changes

2023-10-31 15:00 UTC, leonardomendix approved these changes

2023-10-31 15:29 UTC, merged