[WC-2197]: Add columns visible
mendix/web-widgets pull request #799
Opened 2023-11-02 10:20 UTC by samuelreichert

### Pull request type

New feature (non-breaking change which adds functionality)

---

### Description

2023-11-02 12:38 UTC, Andries-Smit commented on packages/pluggableWidgets/datagrid-web/src/Datagrid.xml
> +                            <property key="ignored" type="boolean" defaultValue="false">
Should it be of type `expression`? The visibility should ultimately be conditional to the context of the widget, or is this story not related?
https://github.com/mendix/web-widgets/pull/744/files#diff-1050db0f2523af8a57f4c60ce7cca6633bb42748354221aa4de8abcc1495a1f4R111

2023-11-03 08:57 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
> +    const notIgnoredColumns = removeIgnoredColumns(columns);
We should not ignore removed columns as we need full array of columns to maintain correct order.
In short, this should always be true `columnsHidden.length === props.columns.length`

2023-11-03 08:58 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
> +        columnsHidden: notIgnoredColumns!.flatMap(column => (column.hidden ? [column.columnNumber] : [])),
```suggestion
        columnsHidden: notIgnoredColumns!.flatMap(column => (column.hidden || column.ignored ? [column.columnNumber] : [])),
```

2023-11-03 19:18 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
> +        columns: columns!,
What? Why you need `!`? Columns coming from the property.

2023-11-03 19:20 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/helpers/ColumnPreview.tsx
> +        this.ignored = props.ignored === "true";
For preview we can just set this field to `false`.

2023-11-06 07:55 UTC, samuelreichert commented on packages/pluggableWidgets/datagrid-web/typings/global.d.ts
> +        DATAGRID_DATA_EXPORT: string;
This is used on `Export_To_Excel` file, so can't be removed.

2023-11-06 12:16 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/typings/global.d.ts
> +        DATAGRID_DATA_EXPORT: string;
Wait, what?

2023-11-06 12:18 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/typings/global.d.ts
> +        DATAGRID_DATA_EXPORT: string;
Well, that's weird, but then let's leave it as it is.

2023-11-06 12:31 UTC, iobuhov requested changes
Let's change state hook. 
Also, don't forget to add changelog record as well as mention our side contributor.

2023-11-06 12:31 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
I think change needed in code block under "SetColumns".
Right now we reset state to "init" state whenever column expressions is changed. This approach is fine, but have obvious flaw: we loose visibility state. To prevent that, we need to call "computeVisible" as final step. As well as we need to move changes we made in `initColumnsState` function to `computeVisible` function.

2023-11-08 12:18 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
> +        columnsOrder: columns!.map(col => col.columnNumber),
Please, don't use `!`

2023-11-08 12:20 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
> +        columnsHidden: columns!.flatMap(column => (column.hidden || column.ignored ? [column.columnNumber] : [])),
Column should not be included in `columnsHidden` if it's ignored. We should include only columns that has "hidden" true

2023-11-09 09:16 UTC, iobuhov approved these changes
LGTM

2023-11-21 15:44 UTC, iobuhov commented on packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx
> +                const isVisible = !columnsHidden.includes(column.columnNumber);
Can we use `props.hiddenColumns.includes` here instead?

2023-11-21 15:56 UTC, samuelreichert commented on packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx
> +                const isVisible = !columnsHidden.includes(column.columnNumber);
Sure!

2023-11-23 11:59 UTC, iobuhov approved these changes
LGTM

2023-11-28 10:13 UTC, leonardomendix approved these changes

2023-11-29 09:09 UTC, leonardomendix approved these changes

2023-11-29 09:13 UTC, iobuhov approved these changes

2023-11-29 14:04 UTC, merged

2023-11-30 10:00 UTC, Andries-Smit commented
@iobuhov @leonardomendix @samuelreichert  Thank you all, for bringing the feature into the standard!