Feat/wc 2046 gallery keyboard nav 2
mendix/web-widgets pull request #913
Opened 2024-01-30 14:06 UTC by samuelreichert

### Pull request type

New feature (non-breaking change which adds functionality)

---

### Description

2024-01-31 09:49 UTC, iobuhov requested changes

2024-01-31 09:49 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx
> +        desktopItems: props.desktopItems ?? 3,
Let use `1` as a fallback for each breakpoint

2024-01-31 09:49 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/features/item-interaction/__tests__/item-keyboard.spec.tsx
> +    // });
Let remove this test for now?

2024-01-31 09:49 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/features/use-grid-positions.ts
> +import { ObjectItem } from "mendix";
Let rename this file (and others) using camelCase.

2024-01-31 09:49 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/features/item-interaction/use-item-events-controller.ts
>  import { useMemo } from "react";
Move this hook to ItemEventsController

2024-01-31 09:49 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/helpers/use-click-action-helper.ts
> +import { useEffect, useMemo } from "react";
Move this hook to ClickActionHelper.ts

2024-01-31 09:56 UTC, iobuhov requested changes

2024-01-31 09:56 UTC, iobuhov commented on packages/shared/tsconfig-web-widgets/esm-library-with-jsx.json
> +        "lib": ["esnext", "dom"],
Let's replace `esnext` with `ES2022`

2024-01-31 09:57 UTC, iobuhov commented on packages/shared/tsconfig-web-widgets/esm-library-with-jsx.json
> +        "lib": ["esnext", "dom"],
+ Let's update `target` as well

2024-01-31 11:56 UTC, iobuhov approved these changes
LGTM

2024-02-15 20:10 UTC, iobuhov approved these changes
LGTM

2024-02-20 08:45 UTC, leonardomendix submitted a review, later dismissed

2024-02-27 17:03 UTC, leonardomendix approved these changes

2024-02-28 16:08 UTC, iobuhov approved these changes

2024-02-28 16:09 UTC, merged