[WC-2175]: Gallery Multi Selection
mendix/web-widgets pull request #921
Opened 2024-02-05 15:26 UTC by samuelreichert

### Pull request type

New feature (non-breaking change which adds functionality)

---

### Description

2024-02-26 10:22 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/components/ListItem.tsx
> +export function ListItem(props: ListItemProps): ReactElement {
Why `memo` is removed?

2024-02-26 10:31 UTC, samuelreichert commented on packages/pluggableWidgets/gallery-web/src/components/ListItem.tsx
> +export function ListItem(props: ListItemProps): ReactElement {
@iobuhov The list item selection (classes) were not kept up to date with the actual keyboard selection

2024-02-26 11:07 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
> +function getRowIndex(index: number, numberOfColumns: number): number {
4. (NIT) Rename this funciton to `getRowBasedOnItemIndex` and add jsdoc comment explainging what is doing.

2024-02-26 11:07 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
> +export function getPosition(numberOfColumns: number, totalItems: number, index: number): Positions {
5. (NIT) Rename this funciton to `getColumnAndRowBasedOnIndex` and add jsdoc comment explainging what is doing.

2024-02-26 11:07 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
> +export type Positions = {
6. (NIT) Rename this type to `PositionInGrid` (or something with grid in name).

2024-02-26 11:07 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
7. As we're about to introduce a new method, it's a good idea to do the same thing for `SelectActionHelper` - go to the implementation and add a new method `onSelectAdjacentGrid`.

2024-02-26 11:10 UTC, iobuhov requested changes
All in all, PR looks good, but I think we need to split the code into methods to avoid misuse and overload - methods should be simple.

2024-02-26 11:16 UTC, iobuhov commented on packages/pluggableWidgets/gallery-web/src/components/ListItem.tsx
> +export function ListItem(props: ListItemProps): ReactElement {
Ah, I see, but then can we split this component into "container" and "view" and keep the view part wrapped with in memo?

2024-02-26 14:24 UTC, samuelreichert commented on packages/shared/widget-plugin-grid/src/selection/types.ts
In this case I will need both `size` and `numberOfColumns`. For arrow navigation, I still need size, but for the other commands ( "page up", "home", ...) then I can use numberOfColumns.

2024-02-27 17:03 UTC, leonardomendix submitted a review, later dismissed

2024-02-28 10:50 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
> + * @return {number}
Wow, nice 👍

2024-02-28 10:51 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
>          selection = this._diff(selection, itemsToRemove);
There one little thing that I'm afraid of - what about checkboxes in datagrid?
I suspect this change will brake current behavior. But, let's see. I'll approve.
@leonardomendix, can you please test Data Grid as well and report any unusual stfuff?

2024-02-29 11:58 UTC, leonardomendix commented on packages/shared/widget-plugin-grid/src/selection/helpers.ts
>          selection = this._diff(selection, itemsToRemove);
Already checked and it doesn't seem to be affected. Thanks for the heads up.

2024-03-01 10:11 UTC, gjulivan submitted a review, later dismissed

2024-03-04 18:09 UTC, leonardomendix submitted a review, later dismissed

2024-03-05 13:28 UTC, leonardomendix approved these changes

2024-03-05 13:32 UTC, gjulivan submitted a review, later dismissed

2024-03-05 18:18 UTC, leonardomendix approved these changes

2024-03-06 09:35 UTC, iobuhov requested changes

2024-03-06 09:35 UTC, iobuhov commented on packages/shared/widget-plugin-grid/src/selection/__tests__/helpers.spec.ts
> +            expect(gridState()).toEqual([_, _, _, _, x, x, x, x]);
Can we move this test out of this block?
We have new behavior that don't match previous. Can we add just one more block to explain new behavior?

2024-03-06 13:02 UTC, iobuhov approved these changes
LGTM

2024-03-06 14:28 UTC, merged