[WC-2405]: Add barcode format controls to prevent incorrect scanning
mendix/web-widgets pull request #980
Opened 2024-04-08 12:17 UTC by HedwigAR

### Pull request type

Bug fix (non-breaking change which fixes an issue)

---

### Description
We found a case where a Code-39 code was recognized as a RSS-14 code instead. Since we support both of them and they do look very similar, we've added an option to be able to specify what formats should be recognized.
Now the user can select if they want to be able to recognize all formats (this is the option that's enabled by default). If the user does not want this, they'll be able to specify only the codes they're expecting.

### What should be covered while testing?
Testing should check whether it's still possible to recognize all barcode types when `useAllFormats` is set to Yes. Test should also check whether

2024-04-08 12:29 UTC, iobuhov requested changes

2024-04-08 12:29 UTC, iobuhov commented on packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.editorConfig.ts
> +    if (_.useAllFormats) {
The `_` means "unused". But now I see that we use this param, can we assign a full name here?

2024-04-08 12:30 UTC, iobuhov commented
Great PR and description BTW 👍

2024-04-08 13:11 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.editorConfig.ts
> +    if (_.useAllFormats) {
Sure!

2024-04-08 13:14 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +            });
Ofcourse!

2024-04-08 14:09 UTC, iobuhov commented on packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.editorConfig.ts
> +    if (barcodeScannerContainerProps.useAllFormats) {
NIT: in other `editorConfig` files we use `values` as name

2024-04-08 14:11 UTC, iobuhov commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +            args.barcodeFormats!.map((val, index) => (formats[index] = BarcodeFormat[val.barcodeFormat]));
nit:
```suggestion
            formats = args.barcodeFormats!.map(val => BarcodeFormat[val.barcodeFormat]);
```

2024-04-08 14:31 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +            args.barcodeFormats!.map((val, index) => (formats[index] = BarcodeFormat[val.barcodeFormat]));
amazing

2024-04-09 08:10 UTC, iobuhov requested changes

2024-04-09 08:10 UTC, iobuhov commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
Just one last thing: can you please fix eslint warnings in this file?

2024-04-09 08:43 UTC, iobuhov approved these changes

2024-05-28 08:24 UTC, gjulivan commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +        const loop = (resolve: (value: Result) => void, reject: (reason?: Error) => void): void => {
function inside a function, either take it out or useCallback?

2024-05-28 08:25 UTC, gjulivan commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +            videoCropWidth = videoCropWidth / aspectRatioWidth;
if the value here is re-set, isn't the captureCanvas.width and height need to be adjusted again or no?

2024-05-28 08:59 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +            videoCropWidth = videoCropWidth / aspectRatioWidth;
That's a good point, I thought the drawImage would do that automatically but I'm not actually sure. I'll change it

2024-05-30 11:39 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +        const loop = (resolve: (value: Result) => void, reject: (reason?: Error) => void): void => {
I took it out

2024-05-31 13:59 UTC, iobuhov commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +        const element = document.getElementById("canvas-middle-middle")!;
Maybe we should use refs? It's more react way.

2024-05-31 15:04 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +        const element = document.getElementById("canvas-middle-middle")!;
Thanks! I fixed it and used a ref instead, let me know if I did that right

2024-05-31 15:04 UTC, HedwigAR commented on packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts
> +                    (videoRef.current!.videoHeight - videoCropHeight) / 2,
You're right, I got lazy. Should be fixed now

2024-06-06 12:27 UTC, iobuhov approved these changes
LGTM

2024-06-10 09:55 UTC, leonardomendix approved these changes

2024-06-10 15:45 UTC, iobuhov approved these changes

2024-06-11 08:00 UTC, merged